Integration spec
kaizipaul/blog-app pull request #10
Opened 2023-02-21 16:42 UTC by kaizipaul

## Hello Reviewer!
### In this PR, I made the following changes:
- Solved the n+1 problem:
### Before n+1:
![posts_before_n+1](https://user-images.githubusercontent.com/105969119/220405177-7315b20f-572b-4204-993b-9f8ed5c3c87f.png)
![users_before_n+1](https://user-images.githubusercontent.com/105969119/220405283-165d0715-af6f-4174-b7af-979d6b2ecda5.png)

### After n+1:
![posts_after_n+1](https://user-images.githubusercontent.com/105969119/220405808-1d54608c-e047-480a-92e9-430025892dcd.png)
![users_after_n+1](https://user-images.githubusercontent.com/105969119/220405895-06c1595b-2c2d-461a-a71c-d93ea9bdafbd.png)

> Wrote integration tests for:
- Post index page.
- Post show page.
- Users index page.
- Users show page.

2023-02-21 17:41 UTC, TadesseDev requested changes
### Hi @kaizipaul 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)


## Highlights
 - [ ]  Correct GitFlow  ✅
 - [ ]  Good commit history  ✅
 - [ ]  Good PR title/description  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 17:41 UTC, TadesseDev commented on spec/integration/user_index_spec.rb
> +  end
- [ ] Great job @kaizipaul, Your tests are clean and sweet, Yet according to the requirements we need a test that asserts you can see the number of posts `each user` has written. I can see you check for the first user, please add a test case for the second user to make sure your test is accurate all the way.

2023-02-21 17:41 UTC, TadesseDev commented on spec/integration/post_index_spec.rb
> +  end
- [ ] You did a great job @kaizipaul, But here you have missed a test that should be part of this test suit. We need to add a test that asserts you can see a section for pagination if there are more posts than fit on the view. This asserts that pagination is always visible to users. Please add this one.

2023-02-22 09:01 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED 

Hi @kaizipaul , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  All changes requested by previous reviewer implemented
:heavy_check_mark: Before and after screenshots of solving N+1 problem added in the PR description 
:heavy_check_mark:  All test cases added
:heavy_check_mark: All linter checks passing 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 14:59 UTC, merged